### ISSUE TITLE
Control access to dashboard

### ISSUE THREAD

**Issue by lars-t-hansen** [NAICNO/Jobanalyzer#228]
(Spun off from #108.)

The dashboard has some security/privacy implications. The main display and - to an extent - the machine details might be fine to be open to the world but deadweight, cpuhog, and top-consumers reports are more sensitive, and that gets much worse if we fix #91.

**Comment by Sabryr** [comment]
I have shared the jobanalyzer URL with two users to check their own actions. But I see that may be exposing the user names was not a good idea in a URL open to the world. Shall we limit the access to UiO. We can find some workarounds when working from home.

**Comment by lars-t-hansen** [comment]
@Sabryr, right now there is limited information available via the internet, which is the only reason I've not worried too much about who can see what.  (The users will see aggregate system reports and the violators reports, but those are short on detail.)  That will change once I erect the remote-accessible command line queries (#299), as that creates full access to all the logs.  For that reason, those queries will require a username/password.  Anyway, I'll be in the office this week and we can discuss in person.

**Comment by lars-t-hansen** [comment]
Current status:

- main dashboard (no specific user info) is open to the world
- aggregate reports (no specific user info) are open to the world, eg, aggregate nvidia loads etc
- violator and zombie reports, accessible from main dashboard or from "machine details" page, carry user names and information about command line, job duration, start, end etc, but only for the job in question
- interactive query page, as well as command-line query for those who know how to do that, as well as the profile information for a specific job that can be gotten at from the query page, are protected by http basic auth (username/passwd), the passwd database is stored on the naic-report server and is reasonably private

HOWEVER

- queries are executed by http, not https, so people with a network monitor at the right location may see the username/password
- every user that has access has access to data for everyone (everyone is a superuser)

Those two problems are relatively easy to fix in the sense that we can use https and we can add privileges so that user `adam` can only see data about the jobs whose user is `adam`.  Under this scheme, the user would need a login for both `adam` (ml nodes) and `ec-adam` (fox), maybe.  However, that user information is not completely simple since we have data for many systems and we must be careful that `adam` on one cluster is not confused with `adam` on a different cluster.  So in practice the user would need to present credentials in a cluster-relative way.  This creates an admin headache to say the least, but technically it would probably work.  With enough infra one could perhaps subcontract the IM to the IM for the cluster in question.

**Comment by lars-t-hansen** [comment]
I could have sworn I had already written this up here, but anyway, what I'm envisioning is a lightweight capability system where for a fixed login/passwd with permissions to contact sonalyzed - what we already have - there is a set of capabilities on the form username@clustername, granting the login access to records for those users on those clusters, when querying the database.  This generalizes to obvious wildcards: "*@mlx" grants access to all users on that cluster and "*@*" to all users on all clusters.

Likely sonalyzed would apply the capabilities when it creates parameters for the record filtering phase: a capability "*@..." would translate to "-u-" (all users) and "user@..." to "-u user" (specific user), and there would be an additional check in sonalyzed that the cluster makes sense.  But overall this looks cheap, simple, and like very little additional code.  The main complication is that a superuser should be allowed to filter by specific users, so sonalyzed must process any existing -u options in accordance with the permissions.

**Comment by lars-t-hansen** [comment]
The system for authentication and authorization is written up in the file code/sonalyze/AUTH.md, since sometime last week.  Not all is implemented but it hangs together.  We probably won't feel the crunch on this until about january, when we start exposing users to data.

**Comment by lars-t-hansen** [comment]
I think there are two separate issues here:

- there has to be a mapping from a canonical uid (used for authentication) to the user's ID on a cluster (for autorization to access data from the cluster) that is consulted by every query, as described in AUTH.md (user canonical id -> user's cluster id -> query is restricted by the cluster id)

- to the extent that information about various users is available to a user through the dashboard, this has to be implemented by the web server consulting that identity manager, probably, or by the web server delegating the report fetching to sonalyze

I'm going to make #308 about the underlying authentication path (also see #448 which I don't know how to do yet), the present bug will be strictly about the dashboard.

**Comment by lars-t-hansen** [comment]
I think this particular bug is done.  All PII is now behind a password.  Once #308 is fixed, there will be granularity to that information (normal users will only have access to their own info), but that is dashboard-independent.
