### ISSUE TITLE
dash2 window title should reflect the origin of the data

### ISSUE THREAD

**Issue by lars-t-hansen** [NAICNO/Jobanalyzer#231]
Currently the window title is just "Jobanalyzer dashboard", but there will probably be one dashboard per cluster of nodes reporting.  So the window title should say something about that.  This means that we tag the report when the report is generated and transmit the information.  This fits in very well with the change for #230, so maybe do them together.

**Comment by lars-t-hansen** [comment]
When deploying this, we need to redeploy the dash2 HTML+JS, naicreport, and the webload-5m-and-upload.sh script.

**Comment by ashenr** [comment]
New dashboard shows the window title in the format of `<relevant cluster> | NAIC Jobanalyzer`.
Therefore I assume that is already fixed. Additionally do we need to show when the report is generated?
Isn't it make the title too long?

**Comment by lars-t-hansen** [comment]
Probably fine as it is.
