### ISSUE TITLE
Break sonarlog and sonalyze out as separate git repos

### ISSUE THREAD

**Issue by lars-t-hansen** [NAICNO/Jobanalyzer#25]
Certainly sonarlog, which is now a general utility for ingesting and regularizing sonar data, could be given its own git repo under NAICNO and then it can be included as a submodule in other modules that need that functionality, be it sonalyze or [Jobgraph](https://github.com/NordicHPC/jobgraph) or other tools.  It could also be included in the sonar repo, but it's possible it's becoming a little bit too featureful for that to be natural.  Discuss.

I also think that `Jobanalyzer` is a fairly broad idea that probably goes beyond sonalyze, and it would probably make sense for sonalyze to be given its own repo too.  This feels less urgent though.

cc @bast

**Comment by bast** [comment]
I have read and am thinking ... :-)

**Comment by bast** [comment]
Few thoughts just to put them on paper although they don't give any concrete yes or no:
- submodules can create friction for contributors but I am used to them and they are a good tool
- later the module could even become a library/crate on its own
- but submodules are a good intermediate on the way towards separate library and good to use until that library solidifies enough
- being able to define types in just one place would be great but we want to use this in few places so we either need to define it in few places or make it a library

**Comment by lars-t-hansen** [comment]
Another note.  There is a rapidly evolving black-box test suite for sonarlog+sonalyze that is being driven by the availability of some special functionality in sonalyze (new verbs `parse`, `metadata`, `version`), see ./run_tests.sh and ./tests/run_tests.sh in this repo.  This is generally a better/smoother way of writing tests than writing Rust test code, when possible.  If we break out sonarlog as a separate repo / crate / component, we'll want to probably move some of that special sonalyze functionality into a "sonarlog shell", so that we can keep writing tests for sonarlog this way.

**Comment by lars-t-hansen** [comment]
I'm not seeing this happening.  Jobanalyzer is now a large collection of programs with tight interdependencies and a lot of shared code.  Even though the rust bits could be broken out in separate repos, say, I'm making enough changes to eg the sonalyze command line API and the sonarlog data formats that this would become painful quickly.  Going to close this for now.

**Comment by bast** [comment]
:+1:
