### ISSUE TITLE
Deploy sonar prototype to Fox

### ISSUE THREAD

**Issue by lars-t-hansen** [NAICNO/Jobanalyzer#57]
Since sonar and sonalyze now seem to be OK for multi-node systems, we should start collecting data on Fox.

There are some issues around whether Sonar is fast enough, which I'm addressing:

At the moment a Sonar invocation on a Fox node takes about 100ms (this is not a high quality measurement); as NordicHPC/sonar#86 shows, we should be able to cut this time by roughly half.  Deploying to Fox probably does not depend on that fix, but it would be nice to get it done.

We would like to also implement the other three features for performance, reliability, and quality reasons, but it would be good to first measure their impact on Fox nodes with and without GPUs.

- [x] NordicHPC/sonar#86
- [ ] NordicHPC/sonar#44
- [ ] NordicHPC/sonar#87
- [ ] NordicHPC/sonar#88

In addition, there's the deployment checklist:

- [x] Where do the binaries go (shared is OK for now)
- [x] Where do the data go (shared is OK for now)
- [x] Where do the lockfiles go (want a node-local file system)
- [x] How do we run sonar (cron or something else)
- [x] Under what UID do we run sonar (want something that is common between nodes and analysis)
- [x] If cron, are there existing cronfiles on the system (for that UID) that must work?
- [x] ec-fox-sw is not allowed to run crontab
- [x] probably a directory for sonar inside ~ec-fox-sw for sonar cron file and anything else it needs, eg scripts?
- [x] Where do we run the analysis jobs
- [x] How do we ensure that all the jobs stay up all the time
- [x] What will the config files and scripts look like
- [x] #248
- [x] https://github.com/NordicHPC/sonar/issues/123
- [ ] Cleanup lockfiles on reboot
- [x] #253
- [x] #254
- [x] Bring sonar up on all the Fox nodes

**Comment by lars-t-hansen** [comment]
If cron is not possible, it may be possible to trigger the sonar run remotely by ssh, every few minutes, for every node.  Anyway we'll find it out.

**Comment by Sabryr** [comment]
I think for the Fox meeting, better to propose that you would deploy this on 4 compute nodes (2 with GPU and 2 without). i.e. not all at the same time. Even on NRIS side (consultation   with Radovan et all) we ask "some" nodes for the fist round. This gives the admins more assurance on a production system.

**Comment by lars-t-hansen** [comment]
Some results from a meeting

* The sonar binary can go into /cluster/sbin for now, though eventually we want it in /node/bin, but that requires more infra and we want to be more in production than we currently are
* The sonalyze/naicreport binaries can be anywhere really, perhaps in home dir? for user running the analysis
* Sonar data currently go into /cluster/var/sonar
* We use cron on each node
* We run sonar and analysis as `ec-fox-sw`
* We run analysis on the interactive nodes, login-2 was mentioned
* Probably the dashboard will show a host as down if the scripts stop running (b/c heartbeat is gone) and we don't need any more than that

**Comment by lars-t-hansen** [comment]
The analysis is live on Fox (on a small number of nodes).

**Comment by lars-t-hansen** [comment]
The analysis is now live on all Fox nodes.

**Comment by lars-t-hansen** [comment]
Lockfile cleanup can be accomplished by an `@reboot` action in the cron file.

**Comment by lars-t-hansen** [comment]
The analysis is live on Fox cpu, gpu, interactive, and login nodes.  Data are exfiltrated to the remote analysis host.  All blocking bugs are really sonar bugs.

**Comment by lars-t-hansen** [comment]
Lockfile removal: `~sonar` is /var/run/sonar on compute and gpu nodes, and this would work just fine.  But on int and login it is /home/sonar - not fine.  Have petitioned to change homedir to /var/run/sonar on int and login and then just change the script from using /var/tmp to using /var/run/sonar for lockfiles.
