### ISSUE TITLE
Report output directory must be partitioned by cluster

### ISSUE THREAD

**Issue by lars-t-hansen** [NAICNO/Jobanalyzer#617]
Right now we have /data/www/output which holds all reports for all nodes for all clusters.  This isn't going to end well.  The right thing to do is to have /data/www/output/clustername where the clustername is the canonical name, as for everything else we do: /data/www/output/mlx.hpc.uio.no.

While we're in there we should change "output" to "reports", to correspond with the name used everywhere else.

This is a simple server-side fix - basically, the uploader script changes a little - but it will have an impact on the dashboards.  Possibly in a transitional phase we could place symlinks in the "output" folder when we place reports in the new reports/clustername folder.  Or we put files both places.  Alternatively the dashboard should be updated first to attempt to fetch from the new location, and if that fails, to fetch from the old.

Roughly in this order:

- [x] Land #604 
- [x] Deploy new naicreport
- [x] Update naicreport scripts to upload files to cluster-specific output directories /data/www/reports/$cluster
- [x] As a stopgap, also upload /data/www/output
- [x] Upload old dashboard
- [x] Upload new dashboard
- [x] Test
- [ ] Remove the stopgap upload
- [ ] Delete /data/www/output directory
- [x] Set up basic naicreport scripts for saga, now that we're getting data (load-1h, load-5min-and-upload, upload), we might not do the really heavy ones yet

**Comment by lars-t-hansen** [comment]
This is actually urgent.  "c1-10" is basically on every cluster.

**Comment by lars-t-hansen** [comment]
Depends on #604, which is ready to land, I just need a few undisturbed hours to make sure I deploy it right.

**Comment by lars-t-hansen** [comment]
@ashenr For fram, saga, and betzy the reports will only appear in the new segregated output directory for each cluster.  For fox and mlx it will continue to appear both places so that the changeover will be smooth.  We will remove the old output path completely when both the dashboards have been updated.  I can update the old dashboard myself, to test things.

**Comment by lars-t-hansen** [comment]
Data are now coming in to the new output directory and the old-dashboard has been updated to use this exclusively (I hope).  mlx + fox data are also copied to the old directory for now, but it should be safe for changes to the new dashboard to land independently of this patch.

**Comment by ashenr** [comment]
@lars-t-hansen, I uploaded new FE build to the server.

**Comment by lars-t-hansen** [comment]
I will take care of the cleanup.
