### ISSUE TITLE
Why are long-dead hosts being shown?

### ISSUE THREAD

**Issue by lars-t-hansen** [NAICNO/Jobanalyzer#631]
The new hostnames pipeline produces a list of hosts that does not include eg gpu-4 and gpu-4.ib on Fox, these are long dead.  But both the old dashboard and the new dashboard show these:

![image](https://github.com/user-attachments/assets/ddffad5f-1277-482e-900f-2e466b854e09)

What do we need to fix to get rid of them?  Why are they here?  The dashboards should fetch the current hostnames file for the cluster and use that to drive the display (it's the only thing that makes sense and since I could bring the NRIS clusters up in the old dashboard without anything special it's clear that that works, after some fashion).

**Comment by ashenr** [comment]
Can we remove the dead hostnames from the `{clusterName}-at-a-glance.json` as it is generated?
It is doable to fetch the hostnames first, fetch the glance.json next and do the filtering. But it takes two fetches to show the table. I think it's efficient to remove the necessary hosts from the backend and limit to one fetch.

**Comment by lars-t-hansen** [comment]
y, the goal would be to not generate data for the old host names at all, no filtering should really be necessary.  i just need to find out why naicreport is seeing stale data at all.  (ie i think this is my bug really.)

**Comment by lars-t-hansen** [comment]
It turns out there's a really trivial reason for this: naicreport uses the config file to determine the hosts it should list, and these old hosts are in that config.  That was always wrong: it should use a "recent" list of hostnames.  And that is easy to fix now, we obtain the config (as we do now), the host names, and join them, to get a full list of more-or-less live hosts.

**Comment by lars-t-hansen** [comment]
Not so fast... In addition, `sonalyze uptime` surfaces some dead hosts, probably because it too uses the config to drive its action.  So probably the output of uptime must be filtered against the hosts that we want.  Not a big deal, but extra complexity.
