### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by lars-t-hansen** [NAICNO/Jobanalyzer#647]
Since we have a NAIC logo the dashboards should be served with a favicon with this logo.

**Comment by ashenr** [comment]
The favicon is already set but it is not really visible when the browser tab color is a light color.
Dark browser tab
<img width="268" alt="Screenshot 2024-10-30 at 11 36 34 AM" src="https://github.com/user-attachments/assets/deb7aa31-6e5e-49d9-b160-10bcc30564bd">
Light browser tab
<img width="239" alt="Screenshot 2024-10-30 at 11 36 55 AM" src="https://github.com/user-attachments/assets/bd5c4db7-e39b-422d-be91-a8967e952fd0">

We have NAIC logos for dark and light modes. I will check if we can change the favicon based on the user's setting.
