### ISSUE TITLE
Requirements discussion 

### ISSUE THREAD

**Issue by Sabryr** [NAICNO/Jobanalyzer#92]
I am starting this in an issue and then we will move this to a document. There was an older issue, when found must link it here.

**Comment by Sabryr** [comment]
For the NAIC project we have promised the following in the proposal. 

1. Catalogue all AI/ML hardware resources currently in use and are planned to be made
available for consortium. Implement load monitoring and investigate cross institute user
access procedures. Feasibility report on using the resources at disposal as a pool to support overall load to load spikes.
2. Finally, through frequent bench-marking using synthetic and real applications, the infrastructure itself and emerging accelerators’ performance will be analyzed to help users select the best-fitting resources, software frameworks, technical parameters

**Comment by lars-t-hansen** [comment]
Currently our requirements for Jobanalyzer are defined by the use cases in README.md, which are fairly clear, along with some issues in github that are tagged with the "use-case" tag and not yet fully integrated into README.md.  The use cases break down into two groups, sysadmin uses (system utilization and functionality monitoring) and end-user uses (are my jobs using the resources well).

It seems clear that our use cases to some extent address the high-level goals: we can support "load monitoring" and the data we are collecting may be helpful in reporting on "a pool to support overall load to load spikes".  Furthermore the end-user use cases may be helpful in measuring the fit of various benchmarks and real user loads, though that feels a bit underdeveloped at this time, we need more software to test this part against.

In sum, I think we're going in the right direction but it's only by deploying what we have (and more broadly than on the ML nodes) that we will know whether we have something of real utility.

**Comment by Sabryr** [comment]
Then we have work package deliverables 
D2.6 | Profiling tools and resource usage analysis
D2.7 | Document need for further procurement requirement

**Comment by lars-t-hansen** [comment]
Re earlier issues, there's this one: https://github.com/NAICNO/Jobanalyzer/issues/53#issue-1881402324 which doesn't have much meat on the bone but mentions deliverables at least.

**Comment by Sabryr** [comment]
Yes Lars, I am still collecting the info here. I will let you know when I am ready. Sorry for the noise

**Comment by Sabryr** [comment]
3. Load dash board for NAIC participants.
  -  All resource under NAIC should report load. Ideally there should be one page where the load of each site is displayed alongside. 
  - In long term it should be possible to identify load redistribution trends. For example if there was course on Fox during September and this resulted in continues high demand, this should be visible. At the same time if SAGA had unused capacity during this exact period that should be identifiable. The outcome is, some of the Fox users should have been redirected to SAGA, during the course. 
  - We should also report uptime. This would give us some realistic numbers to promise when going on full production.

**Comment by Sabryr** [comment]
This is the summary. 
1. We will have two or three target groups (open for discussion).
     - Admin
     - Users
     - Public/Decision makers 
 2. Admins should be able to get details about job, a user , specific period etc.. to make decisions like 
     - More fitting resources for specific jobs
     - More fitting resources for users
 3. A load dash board for different sites in one place.

**Comment by Sabryr** [comment]
@lars-t-hansen this is what I have now. Can we set realistic deliverables out of this ?

**Comment by lars-t-hansen** [comment]
"Users" is a very heterogeneous group. There may be a need to consider the spectrum, or at least, consider where we focus and how (much) we target the different groups.

**Comment by lars-t-hansen** [comment]
Going to move this discussion + many things from the current README.md into a REQUIREMENTS.md document in this repo.  We should keep using this ticket for further discussion, for now.

**Comment by Sabryr** [comment]
@lars-t-hansen Thank you very much for composing [REQUIREMENTS](https://github.com/NAICNO/Jobanalyzer/blob/main/REQUIREMENTS.md#systems-administrators)
One thing I had missed was, a use-case  where a user wants to find out what resources her job used. This is self evaluation of resources wastage and "is this the best place for me" scenarios. This of course should not try to replicate what a good profiler would do. But something similar to the SLURM command "seff"  can do but with GPU related stats as well. 

```
#9274022 is the jobid
sabryr@SAGA 27-09-2023]$ seff 9274022
Job ID: 9274022
Cluster: saga
User/Group: sabryr/sabryr
State: COMPLETED (exit code 0)
Cores: 1
CPU Utilized: 00:00:07
CPU Efficiency: 63.64% of 00:00:11 core-walltime
Job Wall-clock time: 00:00:11
Memory Utilized: 4.00 KB
Memory Efficiency: 0.00% of 1.00 GB

```

Then, thank you for explicitly including[ security considerations](https://github.com/NAICNO/Jobanalyzer/blob/main/REQUIREMENTS.md#security-and-privacy). This I failed to mention, but good that you thought about it. 

Regards,
Sabry

**Comment by lars-t-hansen** [comment]
@Sabryr, I'll add that.  It's very close to some of the user stories we have already but it's a useful variant to record.  Perhaps I'll restructure the "usr_" user stories somewhat to group them differently.

**Comment by lars-t-hansen** [comment]
I think this is done, for now.  Let's open new bugs with individual additional requirements.
